config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest

  # Defines the root path route ("/")
  root 'web/bulletins#index'

  post 'auth/:provider', to: 'auth#request', as: :auth_request

  scope module: :web do
    resources :auth, param: :provider do
      member do
        get 'callback'
        get 'logout'
      end
    end

    resource :profile, controller: :profile, only: %i[show]

    resources :bulletins, only: %i[index new show create edit update] do
      member do
        patch 'archive'
        patch 'to_moderate'
      end
    end

    namespace :admin do
      resources :categories, only: %i[index new edit update create destroy]
      resources :bulletins,  only: %i[index destroy] do
        member do
          patch 'publish'
          patch 'archive'
          patch 'reject'
        end
      end

      root 'bulletins#on_moderation'
    end
  end
end

app/controllers/web/profile_controller.rb
# frozen_string_literal: true

class Web::ProfileController < Web::ApplicationController
  before_action :user_signed_in?

  def show
    @q = current_user.bulletins.ransack(params[:q])
    @bulletins = @q.result.page(params[:page]).per(10)
  end
end

app/views/web/profile/index.html.slim
h2 = t('profile.index.title')

= link_to t('bulletins.new.title'), new_bulletin_path, class: ["btn","btn-primary"]

.card.mb-3.mt-3.rounded-3.shadow-sm.bg-light
    = search_form_for @q, url: profile_path do |f|
        .d-flex.flex-row.align-items-center.flex-gap-2.justify-content-between.p-2
            .col-6
                = f.label :title_cont
                = f.input :title_cont, label: false, class: "form-control"
            .col-3
                = f.label :state_eq
                = f.input :state_eq, as: :select, collection: Bulletin.aasm.states.map(&:name), label: false, class: "form-control"
            .col-2.d-flex.flex-row
                .col
                    = f.submit t('bulletins.index.search'), class: 'btn btn-primary'
                .col
                    = link_to t('bulletins.index.reset'), url_for, class: 'btn btn-outline-primary'

table.table
    thead
        tr
            th.col = t('bulletins.index.item_title')
            th.col = t('bulletins.index.state')
            th.col = t('bulletins.index.created_at')
            th.col = t('bulletins.index.actions')
    tbody
        - @bulletins.each do |bulletin|
            tr
                td = bulletin.title
                td = bulletin.state
                td = bulletin.created_at
                td
                    .btn-group
                        = link_to t('bulletins.index.show'), bulletin_path(bulletin), class: ["me-1","btn","btn-primary"]
                        - if bulletin.draft? or bulletin.rejected?
                            = link_to t('bulletins.index.edit'), edit_bulletin_path(bulletin), class: ["me-1","btn","btn-primary"]
                        - if bulletin.may_to_moderate?
                            = link_to t('bulletins.index.send_to_moderation'), to_moderate_bulletin_path(bulletin),  data: { turbo_method: :post , turbo_confirm: t('bulletins.to_moderate.confirm')}, class: ["me-1","btn","btn-primary"]
                        - if bulletin.may_archive?
                            = link_to t('bulletins.index.send_to_archive'), archive_bulletin_path(bulletin),  data: { turbo_method: :post , turbo_confirm: t('bulletins.archive.confirm')}, class: ["btn","btn-danger"]

.d-flex.flex-row.justify-content-between.align-items-center
    .col
        = paginate @bulletins
    .col-3
        = page_entries_info @bulletins

app/views/web/profile/show.html.slim
h2 = t('profile.index.title')

= link_to t('bulletins.new.title'), new_bulletin_path, class: %w[btn btn-primary]

= render 'web/bulletins/search', q: @q, search_form_path: profile_path, search_by: :state

table.table
    thead
        tr
            th.col = t('bulletins.index.item_title')
            th.col = t('bulletins.index.state')
            th.col = t('bulletins.index.created_at')
            th.col = t('bulletins.index.actions')
    tbody
        - @bulletins.each do |bulletin|
            tr
                td = bulletin.title
                td = Bulletin.aasm.human_event_name(bulletin.state)
                td = bulletin.created_at
                td
                    .btn-group
                        = link_to t('bulletins.index.show'), bulletin_path(bulletin), class: %w[me-1 btn btn-primary]
                        - if policy(bulletin).edit?
                            = link_to t('bulletins.index.edit'),
                                edit_bulletin_path(bulletin),
                                class: %w[me-1 btn btn-primary]
                        - if bulletin.may_to_moderate?
                            = link_to t('bulletins.index.send_to_moderation'),
                                to_moderate_bulletin_path(bulletin),
                                data: { turbo_method: :patch, turbo_confirm: t('bulletins.to_moderate.confirm') }, class: %w[me-1 btn btn-primary]
                        - if bulletin.may_archive?
                            = link_to t('bulletins.index.send_to_archive'),
                                archive_bulletin_path(bulletin),
                                data: { turbo_method: :patch, turbo_confirm: t('bulletins.archive.confirm') }, class: %w[btn btn-danger]

.d-flex.flex-row.justify-content-between.align-items-center
    .col
        = paginate @bulletins
    .col-3
        = page_entries_info @bulletins