config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker
  get 'manifest' => 'rails/pwa#manifest', as: :pwa_manifest

  # Defines the root path route ("/")
  root 'web/bulletins#index'

  post 'auth/:provider', to: 'auth#request', as: :auth_request

  scope module: :web do
    resources :auth, param: :provider do
      member do
        get 'callback'
        get 'logout'
      end
    end

    resource :profile, controller: :profile, only: %i[show]

    resources :bulletins, only: %i[index new show create edit update] do
      member do
        patch 'archive'
        patch 'to_moderate'
      end
    end

    namespace :admin do
      resources :categories, only: %i[index new edit update create destroy]
      resources :bulletins,  only: %i[index destroy] do
        member do
          patch 'publish'
          patch 'archive'
          patch 'reject'
        end
      end

      root 'bulletins#on_moderation'
    end
  end
end

app/views/layouts/admin.html.slim
= content_for :content do
    .container
        .row
            .col-3
                ul.nav.nav-pills.flex-column
                    li.nav-item = link_to t('bulletins.title.on_moderation'), admin_root_path, class: class_names('nav-link', { active: current_page?(admin_root_path) })
                    li.nav-item = link_to t('bulletins.index.title'), admin_bulletins_path, class: class_names('nav-link', { active: current_page?(admin_bulletins_path) })
                    li.nav-item = link_to t('categories.index.title'), admin_categories_path, class: class_names('nav-link', { active: current_page?(admin_categories_path) })
            .col-9
                = yield

= render template: 'layouts/application'

app/views/layouts/application.html.slim
doctype html
html
    head
        title = t('.title')
        meta name="viewport" content="width=device-width,initial-scale=1"
        meta name="apple-mobile-web-app-capable" content="yes"
        = csrf_meta_tags
        = csp_meta_tag

        = yield :head

        link rel="icon" href="/icon.png" type="image/png"
        link rel="icon" href="/icon.svg" type="image/svg+xml"
        link rel="apple-touch-icon" href="/icon.png"

        = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
        = javascript_include_tag 'application', 'data-turbo-track': 'reload', type: 'module'
    body
        .page-content.container
            = render 'layouts/shared/nav'
            = render 'layouts/shared/flash'
            = content_for?(:content) ? yield(:content) : yield
        footer.bg-light.text-center.fixed-bottom
            .container
                .d-flex.flex-row.justify-content-center
                    .col-1
                        span 2025
                    .col-2
                        a class="nav-link" href="https://www.flaticon.com/free-icons/noticeboard" title="Noticeboard icons created by Mihimihi - Flaticon" Icons from Flaticon